packages:
  - "apps/*"
  - "packages/*"
allowBuilds:
  '@nestjs/core': false
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  esbuild: true
  prisma: true
  sharp: false
  unrs-resolver: false
