/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as ShellIndexRouteImport } from './routes/_shell/index'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'
import { Route as ShellAdminSlugRouteRouteImport } from './routes/_shell/admin/$slug/route'
import { Route as ShellAdminSlugIndexRouteImport } from './routes/_shell/admin/$slug/index'
import { Route as ShellAdminSlugUsersRouteImport } from './routes/_shell/admin/$slug/users'
import { Route as ShellAdminSlugQuestsRouteImport } from './routes/_shell/admin/$slug/quests'
import { Route as ShellAdminSlugProfileRouteImport } from './routes/_shell/admin/$slug/profile'
import { Route as ShellAdminSlugAuditRouteImport } from './routes/_shell/admin/$slug/audit'
import { Route as ShellAdminSlugStoreRouteRouteImport } from './routes/_shell/admin/$slug/store/route'
import { Route as ShellAdminSlugHomeRouteRouteImport } from './routes/_shell/admin/$slug/home/route'
import { Route as ShellAdminSlugStoreIndexRouteImport } from './routes/_shell/admin/$slug/store/index'
import { Route as ShellAdminSlugHomeIndexRouteImport } from './routes/_shell/admin/$slug/home/index'
import { Route as ShellAdminSlugStoreNewRouteImport } from './routes/_shell/admin/$slug/store/new'
import { Route as ShellAdminSlugStoreItemIdRouteImport } from './routes/_shell/admin/$slug/store/$itemId'
import { Route as ShellAdminSlugHomeStoreRouteImport } from './routes/_shell/admin/$slug/home/store'
import { Route as ShellAdminSlugHomeRulesRouteImport } from './routes/_shell/admin/$slug/home/rules'
import { Route as ShellAdminSlugHomePartnersRouteImport } from './routes/_shell/admin/$slug/home/partners'
import { Route as ShellAdminSlugHomeLeaderboardRouteImport } from './routes/_shell/admin/$slug/home/leaderboard'
import { Route as ShellAdminSlugHomePromoRouteRouteImport } from './routes/_shell/admin/$slug/home/promo/route'
import { Route as ShellAdminSlugHomePromoIndexRouteImport } from './routes/_shell/admin/$slug/home/promo/index'
import { Route as ShellAdminSlugHomePromoNewRouteImport } from './routes/_shell/admin/$slug/home/promo/new'
import { Route as ShellAdminSlugHomePromoVariantIdRouteImport } from './routes/_shell/admin/$slug/home/promo/$variantId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellIndexRoute = ShellIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellRoute,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellAdminSlugRouteRoute = ShellAdminSlugRouteRouteImport.update({
  id: '/admin/$slug',
  path: '/admin/$slug',
  getParentRoute: () => ShellRoute,
} as any)
const ShellAdminSlugIndexRoute = ShellAdminSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAdminSlugRouteRoute,
} as any)
const ShellAdminSlugUsersRoute = ShellAdminSlugUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ShellAdminSlugRouteRoute,
} as any)
const ShellAdminSlugQuestsRoute = ShellAdminSlugQuestsRouteImport.update({
  id: '/quests',
  path: '/quests',
  getParentRoute: () => ShellAdminSlugRouteRoute,
} as any)
const ShellAdminSlugProfileRoute = ShellAdminSlugProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ShellAdminSlugRouteRoute,
} as any)
const ShellAdminSlugAuditRoute = ShellAdminSlugAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ShellAdminSlugRouteRoute,
} as any)
const ShellAdminSlugStoreRouteRoute =
  ShellAdminSlugStoreRouteRouteImport.update({
    id: '/store',
    path: '/store',
    getParentRoute: () => ShellAdminSlugRouteRoute,
  } as any)
const ShellAdminSlugHomeRouteRoute = ShellAdminSlugHomeRouteRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ShellAdminSlugRouteRoute,
} as any)
const ShellAdminSlugStoreIndexRoute =
  ShellAdminSlugStoreIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellAdminSlugStoreRouteRoute,
  } as any)
const ShellAdminSlugHomeIndexRoute = ShellAdminSlugHomeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ShellAdminSlugHomeRouteRoute,
} as any)
const ShellAdminSlugStoreNewRoute = ShellAdminSlugStoreNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ShellAdminSlugStoreRouteRoute,
} as any)
const ShellAdminSlugStoreItemIdRoute =
  ShellAdminSlugStoreItemIdRouteImport.update({
    id: '/$itemId',
    path: '/$itemId',
    getParentRoute: () => ShellAdminSlugStoreRouteRoute,
  } as any)
const ShellAdminSlugHomeStoreRoute = ShellAdminSlugHomeStoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => ShellAdminSlugHomeRouteRoute,
} as any)
const ShellAdminSlugHomeRulesRoute = ShellAdminSlugHomeRulesRouteImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => ShellAdminSlugHomeRouteRoute,
} as any)
const ShellAdminSlugHomePartnersRoute =
  ShellAdminSlugHomePartnersRouteImport.update({
    id: '/partners',
    path: '/partners',
    getParentRoute: () => ShellAdminSlugHomeRouteRoute,
  } as any)
const ShellAdminSlugHomeLeaderboardRoute =
  ShellAdminSlugHomeLeaderboardRouteImport.update({
    id: '/leaderboard',
    path: '/leaderboard',
    getParentRoute: () => ShellAdminSlugHomeRouteRoute,
  } as any)
const ShellAdminSlugHomePromoRouteRoute =
  ShellAdminSlugHomePromoRouteRouteImport.update({
    id: '/promo',
    path: '/promo',
    getParentRoute: () => ShellAdminSlugHomeRouteRoute,
  } as any)
const ShellAdminSlugHomePromoIndexRoute =
  ShellAdminSlugHomePromoIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ShellAdminSlugHomePromoRouteRoute,
  } as any)
const ShellAdminSlugHomePromoNewRoute =
  ShellAdminSlugHomePromoNewRouteImport.update({
    id: '/new',
    path: '/new',
    getParentRoute: () => ShellAdminSlugHomePromoRouteRoute,
  } as any)
const ShellAdminSlugHomePromoVariantIdRoute =
  ShellAdminSlugHomePromoVariantIdRouteImport.update({
    id: '/$variantId',
    path: '/$variantId',
    getParentRoute: () => ShellAdminSlugHomePromoRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ShellIndexRoute
  '/login': typeof LoginRoute
  '/admin/$slug': typeof ShellAdminSlugRouteRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/$slug/home': typeof ShellAdminSlugHomeRouteRouteWithChildren
  '/admin/$slug/store': typeof ShellAdminSlugStoreRouteRouteWithChildren
  '/admin/$slug/audit': typeof ShellAdminSlugAuditRoute
  '/admin/$slug/profile': typeof ShellAdminSlugProfileRoute
  '/admin/$slug/quests': typeof ShellAdminSlugQuestsRoute
  '/admin/$slug/users': typeof ShellAdminSlugUsersRoute
  '/admin/$slug/': typeof ShellAdminSlugIndexRoute
  '/admin/$slug/home/promo': typeof ShellAdminSlugHomePromoRouteRouteWithChildren
  '/admin/$slug/home/leaderboard': typeof ShellAdminSlugHomeLeaderboardRoute
  '/admin/$slug/home/partners': typeof ShellAdminSlugHomePartnersRoute
  '/admin/$slug/home/rules': typeof ShellAdminSlugHomeRulesRoute
  '/admin/$slug/home/store': typeof ShellAdminSlugHomeStoreRoute
  '/admin/$slug/store/$itemId': typeof ShellAdminSlugStoreItemIdRoute
  '/admin/$slug/store/new': typeof ShellAdminSlugStoreNewRoute
  '/admin/$slug/home/': typeof ShellAdminSlugHomeIndexRoute
  '/admin/$slug/store/': typeof ShellAdminSlugStoreIndexRoute
  '/admin/$slug/home/promo/$variantId': typeof ShellAdminSlugHomePromoVariantIdRoute
  '/admin/$slug/home/promo/new': typeof ShellAdminSlugHomePromoNewRoute
  '/admin/$slug/home/promo/': typeof ShellAdminSlugHomePromoIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof ShellIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/admin/$slug/audit': typeof ShellAdminSlugAuditRoute
  '/admin/$slug/profile': typeof ShellAdminSlugProfileRoute
  '/admin/$slug/quests': typeof ShellAdminSlugQuestsRoute
  '/admin/$slug/users': typeof ShellAdminSlugUsersRoute
  '/admin/$slug': typeof ShellAdminSlugIndexRoute
  '/admin/$slug/home/leaderboard': typeof ShellAdminSlugHomeLeaderboardRoute
  '/admin/$slug/home/partners': typeof ShellAdminSlugHomePartnersRoute
  '/admin/$slug/home/rules': typeof ShellAdminSlugHomeRulesRoute
  '/admin/$slug/home/store': typeof ShellAdminSlugHomeStoreRoute
  '/admin/$slug/store/$itemId': typeof ShellAdminSlugStoreItemIdRoute
  '/admin/$slug/store/new': typeof ShellAdminSlugStoreNewRoute
  '/admin/$slug/home': typeof ShellAdminSlugHomeIndexRoute
  '/admin/$slug/store': typeof ShellAdminSlugStoreIndexRoute
  '/admin/$slug/home/promo/$variantId': typeof ShellAdminSlugHomePromoVariantIdRoute
  '/admin/$slug/home/promo/new': typeof ShellAdminSlugHomePromoNewRoute
  '/admin/$slug/home/promo': typeof ShellAdminSlugHomePromoIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_shell': typeof ShellRouteWithChildren
  '/login': typeof LoginRoute
  '/_shell/': typeof ShellIndexRoute
  '/_shell/admin/$slug': typeof ShellAdminSlugRouteRouteWithChildren
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/_shell/admin/$slug/home': typeof ShellAdminSlugHomeRouteRouteWithChildren
  '/_shell/admin/$slug/store': typeof ShellAdminSlugStoreRouteRouteWithChildren
  '/_shell/admin/$slug/audit': typeof ShellAdminSlugAuditRoute
  '/_shell/admin/$slug/profile': typeof ShellAdminSlugProfileRoute
  '/_shell/admin/$slug/quests': typeof ShellAdminSlugQuestsRoute
  '/_shell/admin/$slug/users': typeof ShellAdminSlugUsersRoute
  '/_shell/admin/$slug/': typeof ShellAdminSlugIndexRoute
  '/_shell/admin/$slug/home/promo': typeof ShellAdminSlugHomePromoRouteRouteWithChildren
  '/_shell/admin/$slug/home/leaderboard': typeof ShellAdminSlugHomeLeaderboardRoute
  '/_shell/admin/$slug/home/partners': typeof ShellAdminSlugHomePartnersRoute
  '/_shell/admin/$slug/home/rules': typeof ShellAdminSlugHomeRulesRoute
  '/_shell/admin/$slug/home/store': typeof ShellAdminSlugHomeStoreRoute
  '/_shell/admin/$slug/store/$itemId': typeof ShellAdminSlugStoreItemIdRoute
  '/_shell/admin/$slug/store/new': typeof ShellAdminSlugStoreNewRoute
  '/_shell/admin/$slug/home/': typeof ShellAdminSlugHomeIndexRoute
  '/_shell/admin/$slug/store/': typeof ShellAdminSlugStoreIndexRoute
  '/_shell/admin/$slug/home/promo/$variantId': typeof ShellAdminSlugHomePromoVariantIdRoute
  '/_shell/admin/$slug/home/promo/new': typeof ShellAdminSlugHomePromoNewRoute
  '/_shell/admin/$slug/home/promo/': typeof ShellAdminSlugHomePromoIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/$slug'
    | '/auth/google/callback'
    | '/admin/$slug/home'
    | '/admin/$slug/store'
    | '/admin/$slug/audit'
    | '/admin/$slug/profile'
    | '/admin/$slug/quests'
    | '/admin/$slug/users'
    | '/admin/$slug/'
    | '/admin/$slug/home/promo'
    | '/admin/$slug/home/leaderboard'
    | '/admin/$slug/home/partners'
    | '/admin/$slug/home/rules'
    | '/admin/$slug/home/store'
    | '/admin/$slug/store/$itemId'
    | '/admin/$slug/store/new'
    | '/admin/$slug/home/'
    | '/admin/$slug/store/'
    | '/admin/$slug/home/promo/$variantId'
    | '/admin/$slug/home/promo/new'
    | '/admin/$slug/home/promo/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/auth/google/callback'
    | '/admin/$slug/audit'
    | '/admin/$slug/profile'
    | '/admin/$slug/quests'
    | '/admin/$slug/users'
    | '/admin/$slug'
    | '/admin/$slug/home/leaderboard'
    | '/admin/$slug/home/partners'
    | '/admin/$slug/home/rules'
    | '/admin/$slug/home/store'
    | '/admin/$slug/store/$itemId'
    | '/admin/$slug/store/new'
    | '/admin/$slug/home'
    | '/admin/$slug/store'
    | '/admin/$slug/home/promo/$variantId'
    | '/admin/$slug/home/promo/new'
    | '/admin/$slug/home/promo'
  id:
    | '__root__'
    | '/_shell'
    | '/login'
    | '/_shell/'
    | '/_shell/admin/$slug'
    | '/auth/google/callback'
    | '/_shell/admin/$slug/home'
    | '/_shell/admin/$slug/store'
    | '/_shell/admin/$slug/audit'
    | '/_shell/admin/$slug/profile'
    | '/_shell/admin/$slug/quests'
    | '/_shell/admin/$slug/users'
    | '/_shell/admin/$slug/'
    | '/_shell/admin/$slug/home/promo'
    | '/_shell/admin/$slug/home/leaderboard'
    | '/_shell/admin/$slug/home/partners'
    | '/_shell/admin/$slug/home/rules'
    | '/_shell/admin/$slug/home/store'
    | '/_shell/admin/$slug/store/$itemId'
    | '/_shell/admin/$slug/store/new'
    | '/_shell/admin/$slug/home/'
    | '/_shell/admin/$slug/store/'
    | '/_shell/admin/$slug/home/promo/$variantId'
    | '/_shell/admin/$slug/home/promo/new'
    | '/_shell/admin/$slug/home/promo/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ShellRoute: typeof ShellRouteWithChildren
  LoginRoute: typeof LoginRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/': {
      id: '/_shell/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ShellIndexRouteImport
      parentRoute: typeof ShellRoute
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/admin/$slug': {
      id: '/_shell/admin/$slug'
      path: '/admin/$slug'
      fullPath: '/admin/$slug'
      preLoaderRoute: typeof ShellAdminSlugRouteRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/admin/$slug/': {
      id: '/_shell/admin/$slug/'
      path: '/'
      fullPath: '/admin/$slug/'
      preLoaderRoute: typeof ShellAdminSlugIndexRouteImport
      parentRoute: typeof ShellAdminSlugRouteRoute
    }
    '/_shell/admin/$slug/users': {
      id: '/_shell/admin/$slug/users'
      path: '/users'
      fullPath: '/admin/$slug/users'
      preLoaderRoute: typeof ShellAdminSlugUsersRouteImport
      parentRoute: typeof ShellAdminSlugRouteRoute
    }
    '/_shell/admin/$slug/quests': {
      id: '/_shell/admin/$slug/quests'
      path: '/quests'
      fullPath: '/admin/$slug/quests'
      preLoaderRoute: typeof ShellAdminSlugQuestsRouteImport
      parentRoute: typeof ShellAdminSlugRouteRoute
    }
    '/_shell/admin/$slug/profile': {
      id: '/_shell/admin/$slug/profile'
      path: '/profile'
      fullPath: '/admin/$slug/profile'
      preLoaderRoute: typeof ShellAdminSlugProfileRouteImport
      parentRoute: typeof ShellAdminSlugRouteRoute
    }
    '/_shell/admin/$slug/audit': {
      id: '/_shell/admin/$slug/audit'
      path: '/audit'
      fullPath: '/admin/$slug/audit'
      preLoaderRoute: typeof ShellAdminSlugAuditRouteImport
      parentRoute: typeof ShellAdminSlugRouteRoute
    }
    '/_shell/admin/$slug/store': {
      id: '/_shell/admin/$slug/store'
      path: '/store'
      fullPath: '/admin/$slug/store'
      preLoaderRoute: typeof ShellAdminSlugStoreRouteRouteImport
      parentRoute: typeof ShellAdminSlugRouteRoute
    }
    '/_shell/admin/$slug/home': {
      id: '/_shell/admin/$slug/home'
      path: '/home'
      fullPath: '/admin/$slug/home'
      preLoaderRoute: typeof ShellAdminSlugHomeRouteRouteImport
      parentRoute: typeof ShellAdminSlugRouteRoute
    }
    '/_shell/admin/$slug/store/': {
      id: '/_shell/admin/$slug/store/'
      path: '/'
      fullPath: '/admin/$slug/store/'
      preLoaderRoute: typeof ShellAdminSlugStoreIndexRouteImport
      parentRoute: typeof ShellAdminSlugStoreRouteRoute
    }
    '/_shell/admin/$slug/home/': {
      id: '/_shell/admin/$slug/home/'
      path: '/'
      fullPath: '/admin/$slug/home/'
      preLoaderRoute: typeof ShellAdminSlugHomeIndexRouteImport
      parentRoute: typeof ShellAdminSlugHomeRouteRoute
    }
    '/_shell/admin/$slug/store/new': {
      id: '/_shell/admin/$slug/store/new'
      path: '/new'
      fullPath: '/admin/$slug/store/new'
      preLoaderRoute: typeof ShellAdminSlugStoreNewRouteImport
      parentRoute: typeof ShellAdminSlugStoreRouteRoute
    }
    '/_shell/admin/$slug/store/$itemId': {
      id: '/_shell/admin/$slug/store/$itemId'
      path: '/$itemId'
      fullPath: '/admin/$slug/store/$itemId'
      preLoaderRoute: typeof ShellAdminSlugStoreItemIdRouteImport
      parentRoute: typeof ShellAdminSlugStoreRouteRoute
    }
    '/_shell/admin/$slug/home/store': {
      id: '/_shell/admin/$slug/home/store'
      path: '/store'
      fullPath: '/admin/$slug/home/store'
      preLoaderRoute: typeof ShellAdminSlugHomeStoreRouteImport
      parentRoute: typeof ShellAdminSlugHomeRouteRoute
    }
    '/_shell/admin/$slug/home/rules': {
      id: '/_shell/admin/$slug/home/rules'
      path: '/rules'
      fullPath: '/admin/$slug/home/rules'
      preLoaderRoute: typeof ShellAdminSlugHomeRulesRouteImport
      parentRoute: typeof ShellAdminSlugHomeRouteRoute
    }
    '/_shell/admin/$slug/home/partners': {
      id: '/_shell/admin/$slug/home/partners'
      path: '/partners'
      fullPath: '/admin/$slug/home/partners'
      preLoaderRoute: typeof ShellAdminSlugHomePartnersRouteImport
      parentRoute: typeof ShellAdminSlugHomeRouteRoute
    }
    '/_shell/admin/$slug/home/leaderboard': {
      id: '/_shell/admin/$slug/home/leaderboard'
      path: '/leaderboard'
      fullPath: '/admin/$slug/home/leaderboard'
      preLoaderRoute: typeof ShellAdminSlugHomeLeaderboardRouteImport
      parentRoute: typeof ShellAdminSlugHomeRouteRoute
    }
    '/_shell/admin/$slug/home/promo': {
      id: '/_shell/admin/$slug/home/promo'
      path: '/promo'
      fullPath: '/admin/$slug/home/promo'
      preLoaderRoute: typeof ShellAdminSlugHomePromoRouteRouteImport
      parentRoute: typeof ShellAdminSlugHomeRouteRoute
    }
    '/_shell/admin/$slug/home/promo/': {
      id: '/_shell/admin/$slug/home/promo/'
      path: '/'
      fullPath: '/admin/$slug/home/promo/'
      preLoaderRoute: typeof ShellAdminSlugHomePromoIndexRouteImport
      parentRoute: typeof ShellAdminSlugHomePromoRouteRoute
    }
    '/_shell/admin/$slug/home/promo/new': {
      id: '/_shell/admin/$slug/home/promo/new'
      path: '/new'
      fullPath: '/admin/$slug/home/promo/new'
      preLoaderRoute: typeof ShellAdminSlugHomePromoNewRouteImport
      parentRoute: typeof ShellAdminSlugHomePromoRouteRoute
    }
    '/_shell/admin/$slug/home/promo/$variantId': {
      id: '/_shell/admin/$slug/home/promo/$variantId'
      path: '/$variantId'
      fullPath: '/admin/$slug/home/promo/$variantId'
      preLoaderRoute: typeof ShellAdminSlugHomePromoVariantIdRouteImport
      parentRoute: typeof ShellAdminSlugHomePromoRouteRoute
    }
  }
}

interface ShellAdminSlugHomePromoRouteRouteChildren {
  ShellAdminSlugHomePromoVariantIdRoute: typeof ShellAdminSlugHomePromoVariantIdRoute
  ShellAdminSlugHomePromoNewRoute: typeof ShellAdminSlugHomePromoNewRoute
  ShellAdminSlugHomePromoIndexRoute: typeof ShellAdminSlugHomePromoIndexRoute
}

const ShellAdminSlugHomePromoRouteRouteChildren: ShellAdminSlugHomePromoRouteRouteChildren =
  {
    ShellAdminSlugHomePromoVariantIdRoute:
      ShellAdminSlugHomePromoVariantIdRoute,
    ShellAdminSlugHomePromoNewRoute: ShellAdminSlugHomePromoNewRoute,
    ShellAdminSlugHomePromoIndexRoute: ShellAdminSlugHomePromoIndexRoute,
  }

const ShellAdminSlugHomePromoRouteRouteWithChildren =
  ShellAdminSlugHomePromoRouteRoute._addFileChildren(
    ShellAdminSlugHomePromoRouteRouteChildren,
  )

interface ShellAdminSlugHomeRouteRouteChildren {
  ShellAdminSlugHomePromoRouteRoute: typeof ShellAdminSlugHomePromoRouteRouteWithChildren
  ShellAdminSlugHomeLeaderboardRoute: typeof ShellAdminSlugHomeLeaderboardRoute
  ShellAdminSlugHomePartnersRoute: typeof ShellAdminSlugHomePartnersRoute
  ShellAdminSlugHomeRulesRoute: typeof ShellAdminSlugHomeRulesRoute
  ShellAdminSlugHomeStoreRoute: typeof ShellAdminSlugHomeStoreRoute
  ShellAdminSlugHomeIndexRoute: typeof ShellAdminSlugHomeIndexRoute
}

const ShellAdminSlugHomeRouteRouteChildren: ShellAdminSlugHomeRouteRouteChildren =
  {
    ShellAdminSlugHomePromoRouteRoute:
      ShellAdminSlugHomePromoRouteRouteWithChildren,
    ShellAdminSlugHomeLeaderboardRoute: ShellAdminSlugHomeLeaderboardRoute,
    ShellAdminSlugHomePartnersRoute: ShellAdminSlugHomePartnersRoute,
    ShellAdminSlugHomeRulesRoute: ShellAdminSlugHomeRulesRoute,
    ShellAdminSlugHomeStoreRoute: ShellAdminSlugHomeStoreRoute,
    ShellAdminSlugHomeIndexRoute: ShellAdminSlugHomeIndexRoute,
  }

const ShellAdminSlugHomeRouteRouteWithChildren =
  ShellAdminSlugHomeRouteRoute._addFileChildren(
    ShellAdminSlugHomeRouteRouteChildren,
  )

interface ShellAdminSlugStoreRouteRouteChildren {
  ShellAdminSlugStoreItemIdRoute: typeof ShellAdminSlugStoreItemIdRoute
  ShellAdminSlugStoreNewRoute: typeof ShellAdminSlugStoreNewRoute
  ShellAdminSlugStoreIndexRoute: typeof ShellAdminSlugStoreIndexRoute
}

const ShellAdminSlugStoreRouteRouteChildren: ShellAdminSlugStoreRouteRouteChildren =
  {
    ShellAdminSlugStoreItemIdRoute: ShellAdminSlugStoreItemIdRoute,
    ShellAdminSlugStoreNewRoute: ShellAdminSlugStoreNewRoute,
    ShellAdminSlugStoreIndexRoute: ShellAdminSlugStoreIndexRoute,
  }

const ShellAdminSlugStoreRouteRouteWithChildren =
  ShellAdminSlugStoreRouteRoute._addFileChildren(
    ShellAdminSlugStoreRouteRouteChildren,
  )

interface ShellAdminSlugRouteRouteChildren {
  ShellAdminSlugHomeRouteRoute: typeof ShellAdminSlugHomeRouteRouteWithChildren
  ShellAdminSlugStoreRouteRoute: typeof ShellAdminSlugStoreRouteRouteWithChildren
  ShellAdminSlugAuditRoute: typeof ShellAdminSlugAuditRoute
  ShellAdminSlugProfileRoute: typeof ShellAdminSlugProfileRoute
  ShellAdminSlugQuestsRoute: typeof ShellAdminSlugQuestsRoute
  ShellAdminSlugUsersRoute: typeof ShellAdminSlugUsersRoute
  ShellAdminSlugIndexRoute: typeof ShellAdminSlugIndexRoute
}

const ShellAdminSlugRouteRouteChildren: ShellAdminSlugRouteRouteChildren = {
  ShellAdminSlugHomeRouteRoute: ShellAdminSlugHomeRouteRouteWithChildren,
  ShellAdminSlugStoreRouteRoute: ShellAdminSlugStoreRouteRouteWithChildren,
  ShellAdminSlugAuditRoute: ShellAdminSlugAuditRoute,
  ShellAdminSlugProfileRoute: ShellAdminSlugProfileRoute,
  ShellAdminSlugQuestsRoute: ShellAdminSlugQuestsRoute,
  ShellAdminSlugUsersRoute: ShellAdminSlugUsersRoute,
  ShellAdminSlugIndexRoute: ShellAdminSlugIndexRoute,
}

const ShellAdminSlugRouteRouteWithChildren =
  ShellAdminSlugRouteRoute._addFileChildren(ShellAdminSlugRouteRouteChildren)

interface ShellRouteChildren {
  ShellIndexRoute: typeof ShellIndexRoute
  ShellAdminSlugRouteRoute: typeof ShellAdminSlugRouteRouteWithChildren
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellIndexRoute: ShellIndexRoute,
  ShellAdminSlugRouteRoute: ShellAdminSlugRouteRouteWithChildren,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  ShellRoute: ShellRouteWithChildren,
  LoginRoute: LoginRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
